% returns the jacobian represented in the base frame
function [J] = getJacobian(wamInfo,q)
    ct = cos(q);
    st = sin(q);
    
    dh_a = wamInfo.arm.dh.a;
    dh_d = wamInfo.arm.dh.d;

    J = [ dh_a(4)*st(1)*st(2)*st(4) - dh_a(4)*ct(4)*(ct(1)*st(3) + ct(2)*ct(3)*st(1)) - dh_a(3)*ct(1)*st(3) - dh_d(3)*st(1)*st(2) - dh_a(3)*ct(2)*ct(3)*st(1) - dh_d(5)*(st(4)*(ct(1)*st(3) + ct(2)*ct(3)*st(1)) + ct(4)*st(1)*st(2)), dh_d(5)*(ct(1)*ct(2)*ct(4) - ct(1)*ct(3)*st(2)*st(4)) + dh_d(3)*ct(1)*ct(2) - dh_a(3)*ct(1)*ct(3)*st(2) - dh_a(4)*ct(1)*ct(2)*st(4) - dh_a(4)*ct(1)*ct(3)*ct(4)*st(2), - dh_a(4)*ct(4)*(ct(3)*st(1) + ct(1)*ct(2)*st(3)) - dh_d(5)*st(4)*(ct(3)*st(1) + ct(1)*ct(2)*st(3)) - dh_a(3)*ct(3)*st(1) - dh_a(3)*ct(1)*ct(2)*st(3), dh_a(4)*st(4)*(st(1)*st(3) - ct(1)*ct(2)*ct(3)) - dh_d(5)*(ct(4)*(st(1)*st(3) - ct(1)*ct(2)*ct(3)) + ct(1)*st(2)*st(4)) - dh_a(4)*ct(1)*ct(4)*st(2);
              dh_d(3)*ct(1)*st(2) - dh_a(4)*ct(4)*(st(1)*st(3) - ct(1)*ct(2)*ct(3)) - dh_d(5)*(st(4)*(st(1)*st(3) - ct(1)*ct(2)*ct(3)) - ct(1)*ct(4)*st(2)) - dh_a(3)*st(1)*st(3) + dh_a(3)*ct(1)*ct(2)*ct(3) - dh_a(4)*ct(1)*st(2)*st(4), dh_d(5)*(ct(2)*ct(4)*st(1) - ct(3)*st(1)*st(2)*st(4)) + dh_d(3)*ct(2)*st(1) - dh_a(3)*ct(3)*st(1)*st(2) - dh_a(4)*ct(2)*st(1)*st(4) - dh_a(4)*ct(3)*ct(4)*st(1)*st(2),   dh_a(4)*ct(4)*(ct(1)*ct(3) - ct(2)*st(1)*st(3)) + dh_d(5)*st(4)*(ct(1)*ct(3) - ct(2)*st(1)*st(3)) + dh_a(3)*ct(1)*ct(3) - dh_a(3)*ct(2)*st(1)*st(3), dh_d(5)*(ct(4)*(ct(1)*st(3) + ct(2)*ct(3)*st(1)) - st(1)*st(2)*st(4)) - dh_a(4)*st(4)*(ct(1)*st(3) + ct(2)*ct(3)*st(1)) - dh_a(4)*ct(4)*st(1)*st(2);
                                                                                                                                                                                                                                        0,                                     dh_a(4)*st(2)*st(4) - dh_d(3)*st(2) - dh_a(3)*ct(2)*ct(3) - dh_d(5)*(ct(4)*st(2) + ct(2)*ct(3)*st(4)) - dh_a(4)*ct(2)*ct(3)*ct(4),                                                                           dh_a(3)*st(2)*st(3) + dh_a(4)*ct(4)*st(2)*st(3) + dh_d(5)*st(2)*st(3)*st(4),                                                         dh_a(4)*ct(3)*st(2)*st(4) - dh_a(4)*ct(2)*ct(4) - dh_d(5)*(ct(2)*st(4) + ct(3)*ct(4)*st(2));
                                                                                                                                                                                                                                        0,                                                                                                                                                                -st(1),                                                                                                                                           ct(1)*st(2),                                                                                                                   - ct(3)*st(1) - ct(1)*ct(2)*st(3);
                                                                                                                                                                                                                                        0,                                                                                                                                                                 ct(1),                                                                                                                                           st(1)*st(2),                                                                                                                     ct(1)*ct(3) - ct(2)*st(1)*st(3);
                                                                                                                                                                                                                                        1,                                                                                                                                                                     0,                                                                                                                                                 ct(2),                                                                                                                                        st(2)*st(3)];
end
